// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BookkeeperProtocol.proto

package bk_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Protocol Versions.
type ProtocolVersion int32

const (
	ProtocolVersion_VERSION_ONE   ProtocolVersion = 1
	ProtocolVersion_VERSION_TWO   ProtocolVersion = 2
	ProtocolVersion_VERSION_THREE ProtocolVersion = 3
)

var ProtocolVersion_name = map[int32]string{
	1: "VERSION_ONE",
	2: "VERSION_TWO",
	3: "VERSION_THREE",
}

var ProtocolVersion_value = map[string]int32{
	"VERSION_ONE":   1,
	"VERSION_TWO":   2,
	"VERSION_THREE": 3,
}

func (x ProtocolVersion) Enum() *ProtocolVersion {
	p := new(ProtocolVersion)
	*p = x
	return p
}

func (x ProtocolVersion) String() string {
	return proto.EnumName(ProtocolVersion_name, int32(x))
}

func (x *ProtocolVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtocolVersion_value, data, "ProtocolVersion")
	if err != nil {
		return err
	}
	*x = ProtocolVersion(value)
	return nil
}

func (ProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{0}
}

//*
// Status codes.
type StatusCode int32

const (
	StatusCode_EOK StatusCode = 0
	// Server side Errors 4xx
	StatusCode_ENOLEDGER StatusCode = 402
	StatusCode_ENOENTRY  StatusCode = 403
	StatusCode_EBADREQ   StatusCode = 404
	// IO/access errors 5xx
	StatusCode_EIO              StatusCode = 501
	StatusCode_EUA              StatusCode = 502
	StatusCode_EBADVERSION      StatusCode = 503
	StatusCode_EFENCED          StatusCode = 504
	StatusCode_EREADONLY        StatusCode = 505
	StatusCode_ETOOMANYREQUESTS StatusCode = 506
)

var StatusCode_name = map[int32]string{
	0:   "EOK",
	402: "ENOLEDGER",
	403: "ENOENTRY",
	404: "EBADREQ",
	501: "EIO",
	502: "EUA",
	503: "EBADVERSION",
	504: "EFENCED",
	505: "EREADONLY",
	506: "ETOOMANYREQUESTS",
}

var StatusCode_value = map[string]int32{
	"EOK":              0,
	"ENOLEDGER":        402,
	"ENOENTRY":         403,
	"EBADREQ":          404,
	"EIO":              501,
	"EUA":              502,
	"EBADVERSION":      503,
	"EFENCED":          504,
	"EREADONLY":        505,
	"ETOOMANYREQUESTS": 506,
}

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (x *StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusCode_value, data, "StatusCode")
	if err != nil {
		return err
	}
	*x = StatusCode(value)
	return nil
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{1}
}

//*
// Supported operations by this protocol.
type OperationType int32

const (
	OperationType_READ_ENTRY OperationType = 1
	OperationType_ADD_ENTRY  OperationType = 2
	// Not supported yet.
	OperationType_RANGE_READ_ENTRY              OperationType = 3
	OperationType_RANGE_ADD_ENTRY               OperationType = 4
	OperationType_AUTH                          OperationType = 5
	OperationType_WRITE_LAC                     OperationType = 6
	OperationType_READ_LAC                      OperationType = 7
	OperationType_GET_BOOKIE_INFO               OperationType = 8
	OperationType_START_TLS                     OperationType = 9
	OperationType_FORCE_LEDGER                  OperationType = 10
	OperationType_GET_LIST_OF_ENTRIES_OF_LEDGER OperationType = 11
)

var OperationType_name = map[int32]string{
	1:  "READ_ENTRY",
	2:  "ADD_ENTRY",
	3:  "RANGE_READ_ENTRY",
	4:  "RANGE_ADD_ENTRY",
	5:  "AUTH",
	6:  "WRITE_LAC",
	7:  "READ_LAC",
	8:  "GET_BOOKIE_INFO",
	9:  "START_TLS",
	10: "FORCE_LEDGER",
	11: "GET_LIST_OF_ENTRIES_OF_LEDGER",
}

var OperationType_value = map[string]int32{
	"READ_ENTRY":                    1,
	"ADD_ENTRY":                     2,
	"RANGE_READ_ENTRY":              3,
	"RANGE_ADD_ENTRY":               4,
	"AUTH":                          5,
	"WRITE_LAC":                     6,
	"READ_LAC":                      7,
	"GET_BOOKIE_INFO":               8,
	"START_TLS":                     9,
	"FORCE_LEDGER":                  10,
	"GET_LIST_OF_ENTRIES_OF_LEDGER": 11,
}

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (x *OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OperationType_value, data, "OperationType")
	if err != nil {
		return err
	}
	*x = OperationType(value)
	return nil
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{2}
}

type ReadRequest_Flag int32

const (
	ReadRequest_FENCE_LEDGER    ReadRequest_Flag = 1
	ReadRequest_ENTRY_PIGGYBACK ReadRequest_Flag = 2
)

var ReadRequest_Flag_name = map[int32]string{
	1: "FENCE_LEDGER",
	2: "ENTRY_PIGGYBACK",
}

var ReadRequest_Flag_value = map[string]int32{
	"FENCE_LEDGER":    1,
	"ENTRY_PIGGYBACK": 2,
}

func (x ReadRequest_Flag) Enum() *ReadRequest_Flag {
	p := new(ReadRequest_Flag)
	*p = x
	return p
}

func (x ReadRequest_Flag) String() string {
	return proto.EnumName(ReadRequest_Flag_name, int32(x))
}

func (x *ReadRequest_Flag) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReadRequest_Flag_value, data, "ReadRequest_Flag")
	if err != nil {
		return err
	}
	*x = ReadRequest_Flag(value)
	return nil
}

func (ReadRequest_Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{3, 0}
}

type AddRequest_Flag int32

const (
	AddRequest_RECOVERY_ADD AddRequest_Flag = 1
)

var AddRequest_Flag_name = map[int32]string{
	1: "RECOVERY_ADD",
}

var AddRequest_Flag_value = map[string]int32{
	"RECOVERY_ADD": 1,
}

func (x AddRequest_Flag) Enum() *AddRequest_Flag {
	p := new(AddRequest_Flag)
	*p = x
	return p
}

func (x AddRequest_Flag) String() string {
	return proto.EnumName(AddRequest_Flag_name, int32(x))
}

func (x *AddRequest_Flag) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AddRequest_Flag_value, data, "AddRequest_Flag")
	if err != nil {
		return err
	}
	*x = AddRequest_Flag(value)
	return nil
}

func (AddRequest_Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{4, 0}
}

type GetBookieInfoRequest_Flags int32

const (
	GetBookieInfoRequest_TOTAL_DISK_CAPACITY GetBookieInfoRequest_Flags = 1
	GetBookieInfoRequest_FREE_DISK_SPACE     GetBookieInfoRequest_Flags = 2
)

var GetBookieInfoRequest_Flags_name = map[int32]string{
	1: "TOTAL_DISK_CAPACITY",
	2: "FREE_DISK_SPACE",
}

var GetBookieInfoRequest_Flags_value = map[string]int32{
	"TOTAL_DISK_CAPACITY": 1,
	"FREE_DISK_SPACE":     2,
}

func (x GetBookieInfoRequest_Flags) Enum() *GetBookieInfoRequest_Flags {
	p := new(GetBookieInfoRequest_Flags)
	*p = x
	return p
}

func (x GetBookieInfoRequest_Flags) String() string {
	return proto.EnumName(GetBookieInfoRequest_Flags_name, int32(x))
}

func (x *GetBookieInfoRequest_Flags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetBookieInfoRequest_Flags_value, data, "GetBookieInfoRequest_Flags")
	if err != nil {
		return err
	}
	*x = GetBookieInfoRequest_Flags(value)
	return nil
}

func (GetBookieInfoRequest_Flags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{9, 0}
}

//*
// Packet header for all requests.
type BKPacketHeader struct {
	Version              *ProtocolVersion `protobuf:"varint,1,req,name=version,enum=bk.proto.ProtocolVersion" json:"version,omitempty"`
	Operation            *OperationType   `protobuf:"varint,2,req,name=operation,enum=bk.proto.OperationType" json:"operation,omitempty"`
	TxnId                *uint64          `protobuf:"varint,3,req,name=txnId" json:"txnId,omitempty"`
	Priority             *uint32          `protobuf:"varint,4,opt,name=priority,def=0" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BKPacketHeader) Reset()         { *m = BKPacketHeader{} }
func (m *BKPacketHeader) String() string { return proto.CompactTextString(m) }
func (*BKPacketHeader) ProtoMessage()    {}
func (*BKPacketHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{0}
}

func (m *BKPacketHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BKPacketHeader.Unmarshal(m, b)
}
func (m *BKPacketHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BKPacketHeader.Marshal(b, m, deterministic)
}
func (m *BKPacketHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BKPacketHeader.Merge(m, src)
}
func (m *BKPacketHeader) XXX_Size() int {
	return xxx_messageInfo_BKPacketHeader.Size(m)
}
func (m *BKPacketHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BKPacketHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BKPacketHeader proto.InternalMessageInfo

const Default_BKPacketHeader_Priority uint32 = 0

func (m *BKPacketHeader) GetVersion() ProtocolVersion {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ProtocolVersion_VERSION_ONE
}

func (m *BKPacketHeader) GetOperation() OperationType {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return OperationType_READ_ENTRY
}

func (m *BKPacketHeader) GetTxnId() uint64 {
	if m != nil && m.TxnId != nil {
		return *m.TxnId
	}
	return 0
}

func (m *BKPacketHeader) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return Default_BKPacketHeader_Priority
}

type ContextPair struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContextPair) Reset()         { *m = ContextPair{} }
func (m *ContextPair) String() string { return proto.CompactTextString(m) }
func (*ContextPair) ProtoMessage()    {}
func (*ContextPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{1}
}

func (m *ContextPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContextPair.Unmarshal(m, b)
}
func (m *ContextPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContextPair.Marshal(b, m, deterministic)
}
func (m *ContextPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContextPair.Merge(m, src)
}
func (m *ContextPair) XXX_Size() int {
	return xxx_messageInfo_ContextPair.Size(m)
}
func (m *ContextPair) XXX_DiscardUnknown() {
	xxx_messageInfo_ContextPair.DiscardUnknown(m)
}

var xxx_messageInfo_ContextPair proto.InternalMessageInfo

func (m *ContextPair) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ContextPair) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Request struct {
	Header *BKPacketHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	// Requests
	ReadRequest                     *ReadRequest                     `protobuf:"bytes,100,opt,name=readRequest" json:"readRequest,omitempty"`
	AddRequest                      *AddRequest                      `protobuf:"bytes,101,opt,name=addRequest" json:"addRequest,omitempty"`
	AuthRequest                     *AuthMessage                     `protobuf:"bytes,102,opt,name=authRequest" json:"authRequest,omitempty"`
	WriteLacRequest                 *WriteLacRequest                 `protobuf:"bytes,103,opt,name=writeLacRequest" json:"writeLacRequest,omitempty"`
	ReadLacRequest                  *ReadLacRequest                  `protobuf:"bytes,104,opt,name=readLacRequest" json:"readLacRequest,omitempty"`
	GetBookieInfoRequest            *GetBookieInfoRequest            `protobuf:"bytes,105,opt,name=getBookieInfoRequest" json:"getBookieInfoRequest,omitempty"`
	StartTLSRequest                 *StartTLSRequest                 `protobuf:"bytes,106,opt,name=startTLSRequest" json:"startTLSRequest,omitempty"`
	ForceLedgerRequest              *ForceLedgerRequest              `protobuf:"bytes,107,opt,name=forceLedgerRequest" json:"forceLedgerRequest,omitempty"`
	GetListOfEntriesOfLedgerRequest *GetListOfEntriesOfLedgerRequest `protobuf:"bytes,108,opt,name=getListOfEntriesOfLedgerRequest" json:"getListOfEntriesOfLedgerRequest,omitempty"`
	// to pass MDC context
	RequestContext       []*ContextPair `protobuf:"bytes,200,rep,name=requestContext" json:"requestContext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeader() *BKPacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetReadRequest() *ReadRequest {
	if m != nil {
		return m.ReadRequest
	}
	return nil
}

func (m *Request) GetAddRequest() *AddRequest {
	if m != nil {
		return m.AddRequest
	}
	return nil
}

func (m *Request) GetAuthRequest() *AuthMessage {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

func (m *Request) GetWriteLacRequest() *WriteLacRequest {
	if m != nil {
		return m.WriteLacRequest
	}
	return nil
}

func (m *Request) GetReadLacRequest() *ReadLacRequest {
	if m != nil {
		return m.ReadLacRequest
	}
	return nil
}

func (m *Request) GetGetBookieInfoRequest() *GetBookieInfoRequest {
	if m != nil {
		return m.GetBookieInfoRequest
	}
	return nil
}

func (m *Request) GetStartTLSRequest() *StartTLSRequest {
	if m != nil {
		return m.StartTLSRequest
	}
	return nil
}

func (m *Request) GetForceLedgerRequest() *ForceLedgerRequest {
	if m != nil {
		return m.ForceLedgerRequest
	}
	return nil
}

func (m *Request) GetGetListOfEntriesOfLedgerRequest() *GetListOfEntriesOfLedgerRequest {
	if m != nil {
		return m.GetListOfEntriesOfLedgerRequest
	}
	return nil
}

func (m *Request) GetRequestContext() []*ContextPair {
	if m != nil {
		return m.RequestContext
	}
	return nil
}

type ReadRequest struct {
	Flag     *ReadRequest_Flag `protobuf:"varint,100,opt,name=flag,enum=bk.proto.ReadRequest_Flag" json:"flag,omitempty"`
	LedgerId *int64            `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	// entryId will be -1 for reading the LAST_ADD_CONFIRMED entry.
	EntryId *int64 `protobuf:"varint,2,req,name=entryId" json:"entryId,omitempty"`
	// Used while fencing a ledger.
	MasterKey []byte `protobuf:"bytes,3,opt,name=masterKey" json:"masterKey,omitempty"`
	// Used for waiting on last add confirmed update
	PreviousLAC *int64 `protobuf:"varint,4,opt,name=previousLAC" json:"previousLAC,omitempty"`
	// Used as a timeout (in milliseconds) for the long polling request
	TimeOut              *int64   `protobuf:"varint,5,opt,name=timeOut" json:"timeOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{3}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetFlag() ReadRequest_Flag {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return ReadRequest_FENCE_LEDGER
}

func (m *ReadRequest) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *ReadRequest) GetEntryId() int64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

func (m *ReadRequest) GetMasterKey() []byte {
	if m != nil {
		return m.MasterKey
	}
	return nil
}

func (m *ReadRequest) GetPreviousLAC() int64 {
	if m != nil && m.PreviousLAC != nil {
		return *m.PreviousLAC
	}
	return 0
}

func (m *ReadRequest) GetTimeOut() int64 {
	if m != nil && m.TimeOut != nil {
		return *m.TimeOut
	}
	return 0
}

type AddRequest struct {
	Flag                 *AddRequest_Flag `protobuf:"varint,100,opt,name=flag,enum=bk.proto.AddRequest_Flag" json:"flag,omitempty"`
	LedgerId             *int64           `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	EntryId              *int64           `protobuf:"varint,2,req,name=entryId" json:"entryId,omitempty"`
	MasterKey            []byte           `protobuf:"bytes,3,req,name=masterKey" json:"masterKey,omitempty"`
	Body                 []byte           `protobuf:"bytes,4,req,name=body" json:"body,omitempty"`
	WriteFlags           *int32           `protobuf:"varint,5,opt,name=writeFlags" json:"writeFlags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{4}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetFlag() AddRequest_Flag {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return AddRequest_RECOVERY_ADD
}

func (m *AddRequest) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *AddRequest) GetEntryId() int64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

func (m *AddRequest) GetMasterKey() []byte {
	if m != nil {
		return m.MasterKey
	}
	return nil
}

func (m *AddRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *AddRequest) GetWriteFlags() int32 {
	if m != nil && m.WriteFlags != nil {
		return *m.WriteFlags
	}
	return 0
}

type StartTLSRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTLSRequest) Reset()         { *m = StartTLSRequest{} }
func (m *StartTLSRequest) String() string { return proto.CompactTextString(m) }
func (*StartTLSRequest) ProtoMessage()    {}
func (*StartTLSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{5}
}

func (m *StartTLSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTLSRequest.Unmarshal(m, b)
}
func (m *StartTLSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTLSRequest.Marshal(b, m, deterministic)
}
func (m *StartTLSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTLSRequest.Merge(m, src)
}
func (m *StartTLSRequest) XXX_Size() int {
	return xxx_messageInfo_StartTLSRequest.Size(m)
}
func (m *StartTLSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTLSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTLSRequest proto.InternalMessageInfo

type WriteLacRequest struct {
	LedgerId             *int64   `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	Lac                  *int64   `protobuf:"varint,2,req,name=lac" json:"lac,omitempty"`
	MasterKey            []byte   `protobuf:"bytes,3,req,name=masterKey" json:"masterKey,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,req,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteLacRequest) Reset()         { *m = WriteLacRequest{} }
func (m *WriteLacRequest) String() string { return proto.CompactTextString(m) }
func (*WriteLacRequest) ProtoMessage()    {}
func (*WriteLacRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{6}
}

func (m *WriteLacRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteLacRequest.Unmarshal(m, b)
}
func (m *WriteLacRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteLacRequest.Marshal(b, m, deterministic)
}
func (m *WriteLacRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteLacRequest.Merge(m, src)
}
func (m *WriteLacRequest) XXX_Size() int {
	return xxx_messageInfo_WriteLacRequest.Size(m)
}
func (m *WriteLacRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteLacRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteLacRequest proto.InternalMessageInfo

func (m *WriteLacRequest) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *WriteLacRequest) GetLac() int64 {
	if m != nil && m.Lac != nil {
		return *m.Lac
	}
	return 0
}

func (m *WriteLacRequest) GetMasterKey() []byte {
	if m != nil {
		return m.MasterKey
	}
	return nil
}

func (m *WriteLacRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ForceLedgerRequest struct {
	LedgerId             *int64   `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForceLedgerRequest) Reset()         { *m = ForceLedgerRequest{} }
func (m *ForceLedgerRequest) String() string { return proto.CompactTextString(m) }
func (*ForceLedgerRequest) ProtoMessage()    {}
func (*ForceLedgerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{7}
}

func (m *ForceLedgerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceLedgerRequest.Unmarshal(m, b)
}
func (m *ForceLedgerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceLedgerRequest.Marshal(b, m, deterministic)
}
func (m *ForceLedgerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceLedgerRequest.Merge(m, src)
}
func (m *ForceLedgerRequest) XXX_Size() int {
	return xxx_messageInfo_ForceLedgerRequest.Size(m)
}
func (m *ForceLedgerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceLedgerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForceLedgerRequest proto.InternalMessageInfo

func (m *ForceLedgerRequest) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

type ReadLacRequest struct {
	LedgerId             *int64   `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLacRequest) Reset()         { *m = ReadLacRequest{} }
func (m *ReadLacRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLacRequest) ProtoMessage()    {}
func (*ReadLacRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{8}
}

func (m *ReadLacRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLacRequest.Unmarshal(m, b)
}
func (m *ReadLacRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLacRequest.Marshal(b, m, deterministic)
}
func (m *ReadLacRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLacRequest.Merge(m, src)
}
func (m *ReadLacRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLacRequest.Size(m)
}
func (m *ReadLacRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLacRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLacRequest proto.InternalMessageInfo

func (m *ReadLacRequest) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

type GetBookieInfoRequest struct {
	// bitwise OR of Flags
	Requested            *int64   `protobuf:"varint,1,opt,name=requested" json:"requested,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookieInfoRequest) Reset()         { *m = GetBookieInfoRequest{} }
func (m *GetBookieInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookieInfoRequest) ProtoMessage()    {}
func (*GetBookieInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{9}
}

func (m *GetBookieInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookieInfoRequest.Unmarshal(m, b)
}
func (m *GetBookieInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookieInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetBookieInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookieInfoRequest.Merge(m, src)
}
func (m *GetBookieInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookieInfoRequest.Size(m)
}
func (m *GetBookieInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookieInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookieInfoRequest proto.InternalMessageInfo

func (m *GetBookieInfoRequest) GetRequested() int64 {
	if m != nil && m.Requested != nil {
		return *m.Requested
	}
	return 0
}

type GetListOfEntriesOfLedgerRequest struct {
	LedgerId             *int64   `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListOfEntriesOfLedgerRequest) Reset()         { *m = GetListOfEntriesOfLedgerRequest{} }
func (m *GetListOfEntriesOfLedgerRequest) String() string { return proto.CompactTextString(m) }
func (*GetListOfEntriesOfLedgerRequest) ProtoMessage()    {}
func (*GetListOfEntriesOfLedgerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{10}
}

func (m *GetListOfEntriesOfLedgerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListOfEntriesOfLedgerRequest.Unmarshal(m, b)
}
func (m *GetListOfEntriesOfLedgerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListOfEntriesOfLedgerRequest.Marshal(b, m, deterministic)
}
func (m *GetListOfEntriesOfLedgerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListOfEntriesOfLedgerRequest.Merge(m, src)
}
func (m *GetListOfEntriesOfLedgerRequest) XXX_Size() int {
	return xxx_messageInfo_GetListOfEntriesOfLedgerRequest.Size(m)
}
func (m *GetListOfEntriesOfLedgerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListOfEntriesOfLedgerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListOfEntriesOfLedgerRequest proto.InternalMessageInfo

func (m *GetListOfEntriesOfLedgerRequest) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

type Response struct {
	Header *BKPacketHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	// EOK if the underlying request succeeded. Each individual response
	// has a more meaningful status. EBADREQ if we have an unsupported request.
	Status *StatusCode `protobuf:"varint,2,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	// Response
	ReadResponse                     *ReadResponse                     `protobuf:"bytes,100,opt,name=readResponse" json:"readResponse,omitempty"`
	AddResponse                      *AddResponse                      `protobuf:"bytes,101,opt,name=addResponse" json:"addResponse,omitempty"`
	AuthResponse                     *AuthMessage                      `protobuf:"bytes,102,opt,name=authResponse" json:"authResponse,omitempty"`
	WriteLacResponse                 *WriteLacResponse                 `protobuf:"bytes,103,opt,name=writeLacResponse" json:"writeLacResponse,omitempty"`
	ReadLacResponse                  *ReadLacResponse                  `protobuf:"bytes,104,opt,name=readLacResponse" json:"readLacResponse,omitempty"`
	GetBookieInfoResponse            *GetBookieInfoResponse            `protobuf:"bytes,105,opt,name=getBookieInfoResponse" json:"getBookieInfoResponse,omitempty"`
	StartTLSResponse                 *StartTLSResponse                 `protobuf:"bytes,106,opt,name=startTLSResponse" json:"startTLSResponse,omitempty"`
	ForceLedgerResponse              *ForceLedgerResponse              `protobuf:"bytes,107,opt,name=forceLedgerResponse" json:"forceLedgerResponse,omitempty"`
	GetListOfEntriesOfLedgerResponse *GetListOfEntriesOfLedgerResponse `protobuf:"bytes,108,opt,name=getListOfEntriesOfLedgerResponse" json:"getListOfEntriesOfLedgerResponse,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                          `json:"-"`
	XXX_unrecognized                 []byte                            `json:"-"`
	XXX_sizecache                    int32                             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{11}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *BKPacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *Response) GetReadResponse() *ReadResponse {
	if m != nil {
		return m.ReadResponse
	}
	return nil
}

func (m *Response) GetAddResponse() *AddResponse {
	if m != nil {
		return m.AddResponse
	}
	return nil
}

func (m *Response) GetAuthResponse() *AuthMessage {
	if m != nil {
		return m.AuthResponse
	}
	return nil
}

func (m *Response) GetWriteLacResponse() *WriteLacResponse {
	if m != nil {
		return m.WriteLacResponse
	}
	return nil
}

func (m *Response) GetReadLacResponse() *ReadLacResponse {
	if m != nil {
		return m.ReadLacResponse
	}
	return nil
}

func (m *Response) GetGetBookieInfoResponse() *GetBookieInfoResponse {
	if m != nil {
		return m.GetBookieInfoResponse
	}
	return nil
}

func (m *Response) GetStartTLSResponse() *StartTLSResponse {
	if m != nil {
		return m.StartTLSResponse
	}
	return nil
}

func (m *Response) GetForceLedgerResponse() *ForceLedgerResponse {
	if m != nil {
		return m.ForceLedgerResponse
	}
	return nil
}

func (m *Response) GetGetListOfEntriesOfLedgerResponse() *GetListOfEntriesOfLedgerResponse {
	if m != nil {
		return m.GetListOfEntriesOfLedgerResponse
	}
	return nil
}

type ReadResponse struct {
	Status   *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	LedgerId *int64      `protobuf:"varint,2,req,name=ledgerId" json:"ledgerId,omitempty"`
	EntryId  *int64      `protobuf:"varint,3,req,name=entryId" json:"entryId,omitempty"`
	Body     []byte      `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	// Piggyback LAC
	MaxLAC               *int64   `protobuf:"varint,5,opt,name=maxLAC" json:"maxLAC,omitempty"`
	LacUpdateTimestamp   *int64   `protobuf:"varint,6,opt,name=lacUpdateTimestamp" json:"lacUpdateTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{12}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *ReadResponse) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *ReadResponse) GetEntryId() int64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

func (m *ReadResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *ReadResponse) GetMaxLAC() int64 {
	if m != nil && m.MaxLAC != nil {
		return *m.MaxLAC
	}
	return 0
}

func (m *ReadResponse) GetLacUpdateTimestamp() int64 {
	if m != nil && m.LacUpdateTimestamp != nil {
		return *m.LacUpdateTimestamp
	}
	return 0
}

type AddResponse struct {
	Status               *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	LedgerId             *int64      `protobuf:"varint,2,req,name=ledgerId" json:"ledgerId,omitempty"`
	EntryId              *int64      `protobuf:"varint,3,req,name=entryId" json:"entryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{13}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *AddResponse) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *AddResponse) GetEntryId() int64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

type AuthMessage struct {
	AuthPluginName       *string  `protobuf:"bytes,1,req,name=authPluginName" json:"authPluginName,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMessage) Reset()         { *m = AuthMessage{} }
func (m *AuthMessage) String() string { return proto.CompactTextString(m) }
func (*AuthMessage) ProtoMessage()    {}
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{14}
}

func (m *AuthMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMessage.Unmarshal(m, b)
}
func (m *AuthMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMessage.Marshal(b, m, deterministic)
}
func (m *AuthMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMessage.Merge(m, src)
}
func (m *AuthMessage) XXX_Size() int {
	return xxx_messageInfo_AuthMessage.Size(m)
}
func (m *AuthMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMessage proto.InternalMessageInfo

func (m *AuthMessage) GetAuthPluginName() string {
	if m != nil && m.AuthPluginName != nil {
		return *m.AuthPluginName
	}
	return ""
}

func (m *AuthMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type WriteLacResponse struct {
	Status               *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	LedgerId             *int64      `protobuf:"varint,2,req,name=ledgerId" json:"ledgerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WriteLacResponse) Reset()         { *m = WriteLacResponse{} }
func (m *WriteLacResponse) String() string { return proto.CompactTextString(m) }
func (*WriteLacResponse) ProtoMessage()    {}
func (*WriteLacResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{15}
}

func (m *WriteLacResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteLacResponse.Unmarshal(m, b)
}
func (m *WriteLacResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteLacResponse.Marshal(b, m, deterministic)
}
func (m *WriteLacResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteLacResponse.Merge(m, src)
}
func (m *WriteLacResponse) XXX_Size() int {
	return xxx_messageInfo_WriteLacResponse.Size(m)
}
func (m *WriteLacResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteLacResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteLacResponse proto.InternalMessageInfo

func (m *WriteLacResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *WriteLacResponse) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

type ForceLedgerResponse struct {
	Status               *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	LedgerId             *int64      `protobuf:"varint,2,req,name=ledgerId" json:"ledgerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ForceLedgerResponse) Reset()         { *m = ForceLedgerResponse{} }
func (m *ForceLedgerResponse) String() string { return proto.CompactTextString(m) }
func (*ForceLedgerResponse) ProtoMessage()    {}
func (*ForceLedgerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{16}
}

func (m *ForceLedgerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceLedgerResponse.Unmarshal(m, b)
}
func (m *ForceLedgerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceLedgerResponse.Marshal(b, m, deterministic)
}
func (m *ForceLedgerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceLedgerResponse.Merge(m, src)
}
func (m *ForceLedgerResponse) XXX_Size() int {
	return xxx_messageInfo_ForceLedgerResponse.Size(m)
}
func (m *ForceLedgerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceLedgerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForceLedgerResponse proto.InternalMessageInfo

func (m *ForceLedgerResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *ForceLedgerResponse) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

type ReadLacResponse struct {
	Status               *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	LedgerId             *int64      `protobuf:"varint,2,req,name=ledgerId" json:"ledgerId,omitempty"`
	LacBody              []byte      `protobuf:"bytes,3,opt,name=lacBody" json:"lacBody,omitempty"`
	LastEntryBody        []byte      `protobuf:"bytes,4,opt,name=lastEntryBody" json:"lastEntryBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadLacResponse) Reset()         { *m = ReadLacResponse{} }
func (m *ReadLacResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLacResponse) ProtoMessage()    {}
func (*ReadLacResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{17}
}

func (m *ReadLacResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLacResponse.Unmarshal(m, b)
}
func (m *ReadLacResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLacResponse.Marshal(b, m, deterministic)
}
func (m *ReadLacResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLacResponse.Merge(m, src)
}
func (m *ReadLacResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLacResponse.Size(m)
}
func (m *ReadLacResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLacResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLacResponse proto.InternalMessageInfo

func (m *ReadLacResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *ReadLacResponse) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *ReadLacResponse) GetLacBody() []byte {
	if m != nil {
		return m.LacBody
	}
	return nil
}

func (m *ReadLacResponse) GetLastEntryBody() []byte {
	if m != nil {
		return m.LastEntryBody
	}
	return nil
}

type GetBookieInfoResponse struct {
	Status               *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	TotalDiskCapacity    *int64      `protobuf:"varint,2,opt,name=totalDiskCapacity" json:"totalDiskCapacity,omitempty"`
	FreeDiskSpace        *int64      `protobuf:"varint,3,opt,name=freeDiskSpace" json:"freeDiskSpace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBookieInfoResponse) Reset()         { *m = GetBookieInfoResponse{} }
func (m *GetBookieInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookieInfoResponse) ProtoMessage()    {}
func (*GetBookieInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{18}
}

func (m *GetBookieInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookieInfoResponse.Unmarshal(m, b)
}
func (m *GetBookieInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookieInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetBookieInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookieInfoResponse.Merge(m, src)
}
func (m *GetBookieInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookieInfoResponse.Size(m)
}
func (m *GetBookieInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookieInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookieInfoResponse proto.InternalMessageInfo

func (m *GetBookieInfoResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *GetBookieInfoResponse) GetTotalDiskCapacity() int64 {
	if m != nil && m.TotalDiskCapacity != nil {
		return *m.TotalDiskCapacity
	}
	return 0
}

func (m *GetBookieInfoResponse) GetFreeDiskSpace() int64 {
	if m != nil && m.FreeDiskSpace != nil {
		return *m.FreeDiskSpace
	}
	return 0
}

type GetListOfEntriesOfLedgerResponse struct {
	Status                        *StatusCode `protobuf:"varint,1,req,name=status,enum=bk.proto.StatusCode" json:"status,omitempty"`
	LedgerId                      *int64      `protobuf:"varint,2,req,name=ledgerId" json:"ledgerId,omitempty"`
	AvailabilityOfEntriesOfLedger []byte      `protobuf:"bytes,3,opt,name=availabilityOfEntriesOfLedger" json:"availabilityOfEntriesOfLedger,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}    `json:"-"`
	XXX_unrecognized              []byte      `json:"-"`
	XXX_sizecache                 int32       `json:"-"`
}

func (m *GetListOfEntriesOfLedgerResponse) Reset()         { *m = GetListOfEntriesOfLedgerResponse{} }
func (m *GetListOfEntriesOfLedgerResponse) String() string { return proto.CompactTextString(m) }
func (*GetListOfEntriesOfLedgerResponse) ProtoMessage()    {}
func (*GetListOfEntriesOfLedgerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{19}
}

func (m *GetListOfEntriesOfLedgerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListOfEntriesOfLedgerResponse.Unmarshal(m, b)
}
func (m *GetListOfEntriesOfLedgerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListOfEntriesOfLedgerResponse.Marshal(b, m, deterministic)
}
func (m *GetListOfEntriesOfLedgerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListOfEntriesOfLedgerResponse.Merge(m, src)
}
func (m *GetListOfEntriesOfLedgerResponse) XXX_Size() int {
	return xxx_messageInfo_GetListOfEntriesOfLedgerResponse.Size(m)
}
func (m *GetListOfEntriesOfLedgerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListOfEntriesOfLedgerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListOfEntriesOfLedgerResponse proto.InternalMessageInfo

func (m *GetListOfEntriesOfLedgerResponse) GetStatus() StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusCode_EOK
}

func (m *GetListOfEntriesOfLedgerResponse) GetLedgerId() int64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *GetListOfEntriesOfLedgerResponse) GetAvailabilityOfEntriesOfLedger() []byte {
	if m != nil {
		return m.AvailabilityOfEntriesOfLedger
	}
	return nil
}

type StartTLSResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTLSResponse) Reset()         { *m = StartTLSResponse{} }
func (m *StartTLSResponse) String() string { return proto.CompactTextString(m) }
func (*StartTLSResponse) ProtoMessage()    {}
func (*StartTLSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054377d42d427cd0, []int{20}
}

func (m *StartTLSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTLSResponse.Unmarshal(m, b)
}
func (m *StartTLSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTLSResponse.Marshal(b, m, deterministic)
}
func (m *StartTLSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTLSResponse.Merge(m, src)
}
func (m *StartTLSResponse) XXX_Size() int {
	return xxx_messageInfo_StartTLSResponse.Size(m)
}
func (m *StartTLSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTLSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartTLSResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("bk.proto.ProtocolVersion", ProtocolVersion_name, ProtocolVersion_value)
	proto.RegisterEnum("bk.proto.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("bk.proto.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("bk.proto.ReadRequest_Flag", ReadRequest_Flag_name, ReadRequest_Flag_value)
	proto.RegisterEnum("bk.proto.AddRequest_Flag", AddRequest_Flag_name, AddRequest_Flag_value)
	proto.RegisterEnum("bk.proto.GetBookieInfoRequest_Flags", GetBookieInfoRequest_Flags_name, GetBookieInfoRequest_Flags_value)
	proto.RegisterType((*BKPacketHeader)(nil), "bk.proto.BKPacketHeader")
	proto.RegisterType((*ContextPair)(nil), "bk.proto.ContextPair")
	proto.RegisterType((*Request)(nil), "bk.proto.Request")
	proto.RegisterType((*ReadRequest)(nil), "bk.proto.ReadRequest")
	proto.RegisterType((*AddRequest)(nil), "bk.proto.AddRequest")
	proto.RegisterType((*StartTLSRequest)(nil), "bk.proto.StartTLSRequest")
	proto.RegisterType((*WriteLacRequest)(nil), "bk.proto.WriteLacRequest")
	proto.RegisterType((*ForceLedgerRequest)(nil), "bk.proto.ForceLedgerRequest")
	proto.RegisterType((*ReadLacRequest)(nil), "bk.proto.ReadLacRequest")
	proto.RegisterType((*GetBookieInfoRequest)(nil), "bk.proto.GetBookieInfoRequest")
	proto.RegisterType((*GetListOfEntriesOfLedgerRequest)(nil), "bk.proto.GetListOfEntriesOfLedgerRequest")
	proto.RegisterType((*Response)(nil), "bk.proto.Response")
	proto.RegisterType((*ReadResponse)(nil), "bk.proto.ReadResponse")
	proto.RegisterType((*AddResponse)(nil), "bk.proto.AddResponse")
	proto.RegisterType((*AuthMessage)(nil), "bk.proto.AuthMessage")
	proto.RegisterType((*WriteLacResponse)(nil), "bk.proto.WriteLacResponse")
	proto.RegisterType((*ForceLedgerResponse)(nil), "bk.proto.ForceLedgerResponse")
	proto.RegisterType((*ReadLacResponse)(nil), "bk.proto.ReadLacResponse")
	proto.RegisterType((*GetBookieInfoResponse)(nil), "bk.proto.GetBookieInfoResponse")
	proto.RegisterType((*GetListOfEntriesOfLedgerResponse)(nil), "bk.proto.GetListOfEntriesOfLedgerResponse")
	proto.RegisterType((*StartTLSResponse)(nil), "bk.proto.StartTLSResponse")
}

func init() { proto.RegisterFile("BookkeeperProtocol.proto", fileDescriptor_054377d42d427cd0) }

var fileDescriptor_054377d42d427cd0 = []byte{
	// 1495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x6e, 0xdb, 0x46,
	0x16, 0x5e, 0x8a, 0xfe, 0x91, 0x8f, 0x64, 0x99, 0x19, 0xdb, 0x89, 0x92, 0x8d, 0x63, 0x2d, 0xb1,
	0x58, 0x78, 0x8d, 0x44, 0x08, 0xbc, 0x1b, 0x2c, 0x36, 0x40, 0x8b, 0x52, 0xd2, 0xc8, 0x16, 0xac,
	0x88, 0xce, 0x88, 0x4e, 0x60, 0xa0, 0x80, 0x30, 0x96, 0xc6, 0x32, 0x23, 0x59, 0x54, 0xc8, 0x91,
	0x1b, 0xbd, 0x40, 0x6f, 0x0b, 0xb4, 0xbd, 0x29, 0x8a, 0x3e, 0x44, 0xfb, 0x14, 0xbd, 0xea, 0x7d,
	0x2f, 0xfa, 0x18, 0xfd, 0x45, 0x2f, 0x8a, 0x19, 0x52, 0xe2, 0x8f, 0x65, 0x3b, 0x29, 0x8c, 0xde,
	0xcd, 0xcf, 0xf7, 0x7d, 0x67, 0x0e, 0x7d, 0xce, 0x7c, 0x23, 0x43, 0xbe, 0xe4, 0x38, 0xbd, 0x1e,
	0x63, 0x43, 0xe6, 0x1e, 0xb8, 0x0e, 0x77, 0xda, 0x4e, 0xbf, 0x38, 0x14, 0x03, 0x94, 0x3e, 0xee,
	0xf9, 0x23, 0xfd, 0x6b, 0x05, 0x72, 0xa5, 0xfd, 0x03, 0xda, 0xee, 0x31, 0xbe, 0xc7, 0x68, 0x87,
	0xb9, 0xe8, 0x3f, 0xb0, 0x78, 0xce, 0x5c, 0xcf, 0x76, 0x06, 0x79, 0xa5, 0x90, 0xda, 0xca, 0xed,
	0xdc, 0x2d, 0x4e, 0xe0, 0xc5, 0x89, 0xce, 0x0b, 0x1f, 0x40, 0x26, 0x48, 0xf4, 0x04, 0x96, 0x9c,
	0x21, 0x73, 0x29, 0x17, 0xb4, 0x94, 0xa4, 0xdd, 0x09, 0x69, 0xe6, 0x64, 0xcb, 0x1a, 0x0f, 0x19,
	0x09, 0x91, 0x68, 0x0d, 0xe6, 0xf9, 0x9b, 0x41, 0xad, 0x93, 0x57, 0x0b, 0xa9, 0xad, 0x39, 0xe2,
	0x4f, 0xd0, 0x06, 0xa4, 0x87, 0xae, 0xed, 0xb8, 0x36, 0x1f, 0xe7, 0xe7, 0x0a, 0xca, 0xd6, 0xf2,
	0x53, 0xe5, 0x31, 0x99, 0x2e, 0xe9, 0x4f, 0x20, 0x53, 0x76, 0x06, 0x9c, 0xbd, 0xe1, 0x07, 0xd4,
	0x76, 0x91, 0x06, 0x6a, 0x8f, 0x8d, 0xe5, 0x59, 0x97, 0x88, 0x18, 0x0a, 0xd5, 0x73, 0xda, 0x1f,
	0x31, 0x79, 0x90, 0x25, 0xe2, 0x4f, 0xf4, 0x8f, 0x17, 0x60, 0x91, 0xb0, 0xd7, 0x23, 0xe6, 0x71,
	0xf4, 0x18, 0x16, 0x4e, 0x65, 0xb6, 0x92, 0x96, 0xd9, 0xc9, 0x87, 0x67, 0x8d, 0x7f, 0x0d, 0x12,
	0xe0, 0xd0, 0xff, 0x20, 0xe3, 0x32, 0xda, 0x09, 0x04, 0xf2, 0x9d, 0x82, 0xb2, 0x95, 0xd9, 0x59,
	0x0f, 0x69, 0x24, 0xdc, 0x24, 0x51, 0x24, 0xfa, 0x2f, 0x00, 0xed, 0x4c, 0x79, 0x4c, 0xf2, 0xd6,
	0x42, 0x9e, 0x31, 0xdd, 0x23, 0x11, 0x9c, 0x08, 0x47, 0x47, 0xfc, 0x74, 0x42, 0x3b, 0x49, 0x86,
	0x33, 0x46, 0xfc, 0xf4, 0x19, 0xf3, 0x3c, 0xda, 0x65, 0x24, 0x8a, 0x44, 0x65, 0x58, 0xf9, 0xc8,
	0xb5, 0x39, 0xab, 0xd3, 0xf6, 0x84, 0xdc, 0x95, 0xe4, 0xc8, 0x5f, 0xf1, 0x65, 0x1c, 0x40, 0x92,
	0x0c, 0xf4, 0x01, 0xe4, 0x44, 0x0a, 0x11, 0x8d, 0x53, 0xa9, 0x91, 0x8f, 0xe7, 0x1b, 0x91, 0x48,
	0xe0, 0x11, 0x81, 0xb5, 0x2e, 0xe3, 0xa2, 0x00, 0x6d, 0x56, 0x1b, 0x9c, 0x38, 0x13, 0x1d, 0x5b,
	0xea, 0x3c, 0x08, 0x75, 0x76, 0x67, 0xa0, 0xc8, 0x4c, 0xae, 0x48, 0xcd, 0xe3, 0xd4, 0xe5, 0x56,
	0xbd, 0x39, 0x91, 0x7b, 0x95, 0x4c, 0xad, 0x19, 0x07, 0x90, 0x24, 0x03, 0xd5, 0x01, 0x9d, 0x38,
	0x6e, 0x9b, 0xd5, 0x59, 0xa7, 0xcb, 0xdc, 0x89, 0x4e, 0x4f, 0xea, 0xdc, 0x0f, 0x75, 0xaa, 0x17,
	0x30, 0x64, 0x06, 0x0f, 0x79, 0xb0, 0xd9, 0x65, 0xbc, 0x6e, 0x7b, 0xdc, 0x3c, 0xc1, 0x03, 0xee,
	0xda, 0xcc, 0x33, 0x4f, 0xe2, 0xd2, 0x7d, 0x29, 0xfd, 0xef, 0x58, 0xc6, 0x57, 0x11, 0xc8, 0x75,
	0x8a, 0xe8, 0x7d, 0xf1, 0xd7, 0x91, 0xc3, 0xa0, 0x0d, 0xf2, 0xdf, 0x2a, 0x05, 0x35, 0x5e, 0x1f,
	0x91, 0x06, 0x21, 0x09, 0xb4, 0xfe, 0xbb, 0x02, 0x99, 0x48, 0xb9, 0xa2, 0x22, 0xcc, 0x9d, 0xf4,
	0x69, 0x57, 0xd6, 0x74, 0x6e, 0xe7, 0xde, 0xcc, 0x9a, 0x2e, 0x56, 0xfb, 0xb4, 0x4b, 0x24, 0x0e,
	0xdd, 0x83, 0x74, 0x5f, 0x1e, 0xa8, 0xd6, 0x91, 0xed, 0xa3, 0x92, 0xe9, 0x1c, 0xe5, 0x61, 0x91,
	0x0d, 0xb8, 0x3b, 0xae, 0x75, 0x64, 0xf3, 0xa9, 0x64, 0x32, 0x45, 0xf7, 0x61, 0xe9, 0x8c, 0x7a,
	0x9c, 0xb9, 0xfb, 0x6c, 0x9c, 0x57, 0x0b, 0xca, 0x56, 0x96, 0x84, 0x0b, 0xa8, 0x00, 0x99, 0xa1,
	0xcb, 0xce, 0x6d, 0x67, 0xe4, 0xd5, 0x8d, 0xb2, 0xec, 0x7a, 0x95, 0x44, 0x97, 0x84, 0x32, 0xb7,
	0xcf, 0x98, 0x39, 0xe2, 0xf9, 0x79, 0xb9, 0x3b, 0x99, 0xea, 0x8f, 0x60, 0x4e, 0x9c, 0x0e, 0x69,
	0x90, 0xad, 0xe2, 0x46, 0x19, 0xb7, 0xea, 0xb8, 0xb2, 0x8b, 0x89, 0xa6, 0xa0, 0x55, 0x58, 0xc1,
	0x0d, 0x8b, 0x1c, 0xb5, 0x0e, 0x6a, 0xbb, 0xbb, 0x47, 0x25, 0xa3, 0xbc, 0xaf, 0xa5, 0xf4, 0x1f,
	0x14, 0x80, 0xb0, 0xeb, 0xd0, 0xa3, 0x58, 0xf6, 0x77, 0x67, 0x75, 0xe6, 0x8d, 0x27, 0x9f, 0x8a,
	0x27, 0x8f, 0x60, 0xee, 0xd8, 0xe9, 0x88, 0xbb, 0x4e, 0x6c, 0xc8, 0x31, 0x7a, 0x00, 0x20, 0xbb,
	0x52, 0x84, 0xf6, 0x64, 0xc6, 0xf3, 0x24, 0xb2, 0xa2, 0xe7, 0xc3, 0xa4, 0x09, 0x2e, 0x9b, 0x2f,
	0x30, 0x39, 0x6a, 0x19, 0x95, 0x8a, 0xa6, 0xe8, 0xb7, 0x60, 0x25, 0xd1, 0x05, 0xfa, 0x6b, 0x58,
	0x49, 0xf4, 0xfc, 0x95, 0x79, 0x68, 0xa0, 0xf6, 0x69, 0x3b, 0xc8, 0x41, 0x0c, 0xdf, 0xfd, 0xfc,
	0xfa, 0x63, 0x40, 0x17, 0x7b, 0xe8, 0xaa, 0xa8, 0xfa, 0x43, 0xc8, 0xc5, 0x2f, 0x95, 0x2b, 0xd1,
	0x3d, 0x58, 0x9b, 0x75, 0x75, 0x88, 0x93, 0x06, 0xe5, 0xce, 0x04, 0x49, 0x14, 0x4a, 0xb8, 0xa0,
	0x3f, 0x81, 0x79, 0xf9, 0xf9, 0xd0, 0x1d, 0x58, 0xb5, 0x4c, 0xcb, 0xa8, 0xb7, 0x2a, 0xb5, 0xe6,
	0x7e, 0xab, 0x6c, 0x1c, 0x18, 0xe5, 0x9a, 0x75, 0xe4, 0x97, 0x4c, 0x95, 0x60, 0xec, 0xaf, 0x37,
	0x0f, 0x8c, 0x32, 0xd6, 0x52, 0xfa, 0x7b, 0xb0, 0x79, 0x4d, 0xd7, 0x5e, 0x79, 0xd6, 0x4f, 0x16,
	0x20, 0x4d, 0x98, 0x37, 0x74, 0x06, 0x1e, 0xfb, 0x13, 0xd6, 0xf3, 0x10, 0x16, 0x3c, 0x4e, 0xf9,
	0xc8, 0x0b, 0x8c, 0x75, 0x2d, 0x76, 0xdd, 0xf1, 0x91, 0x57, 0x76, 0x3a, 0x8c, 0x04, 0x18, 0xf4,
	0x14, 0xb2, 0xbe, 0xfd, 0xf8, 0xf1, 0x02, 0xa7, 0xba, 0x9d, 0xec, 0x6a, 0x7f, 0x97, 0xc4, 0xb0,
	0xd2, 0x75, 0x3a, 0x21, 0x95, 0x5d, 0x70, 0x9d, 0x70, 0x93, 0x44, 0x91, 0xe8, 0xff, 0x90, 0xf5,
	0x4d, 0x28, 0x60, 0x5e, 0xe9, 0x57, 0x31, 0x28, 0xaa, 0x82, 0x16, 0xda, 0x4f, 0x40, 0xf7, 0x1d,
	0xeb, 0xde, 0x2c, 0xc7, 0x0a, 0xa2, 0x5f, 0xe0, 0x08, 0x77, 0x98, 0x7a, 0x50, 0x20, 0x73, 0x9a,
	0x74, 0x07, 0x12, 0x07, 0x90, 0x24, 0x03, 0x1d, 0xc2, 0x7a, 0xc2, 0x7a, 0x02, 0x29, 0xdf, 0xb7,
	0x36, 0x2f, 0xf5, 0xad, 0x40, 0x70, 0x36, 0x5b, 0xe4, 0x18, 0xfa, 0x50, 0xa0, 0xf8, 0x2a, 0x99,
	0x63, 0x33, 0x81, 0x20, 0x17, 0x38, 0xc8, 0x84, 0xd5, 0x98, 0x09, 0x05, 0x52, 0xbe, 0x7b, 0x6d,
	0x5c, 0xe2, 0x5e, 0x81, 0xda, 0x2c, 0x26, 0x3a, 0x87, 0xc2, 0xe5, 0x6e, 0x13, 0xa8, 0xfb, 0x06,
	0xb6, 0xfd, 0x36, 0x06, 0x16, 0x84, 0xba, 0x56, 0x53, 0xff, 0x4e, 0x81, 0x6c, 0xb4, 0x0e, 0x23,
	0x35, 0xae, 0xbc, 0x45, 0x8d, 0x47, 0x9b, 0x2d, 0x75, 0xf9, 0x25, 0xac, 0xc6, 0x2f, 0xe1, 0xf0,
	0x9a, 0x52, 0xa6, 0xd7, 0xec, 0x6d, 0x58, 0x38, 0xa3, 0x6f, 0x84, 0xe5, 0xf8, 0xa6, 0x12, 0xcc,
	0x50, 0x11, 0x50, 0x9f, 0xb6, 0x0f, 0x87, 0x1d, 0xca, 0x99, 0x65, 0x9f, 0x31, 0x8f, 0xd3, 0xb3,
	0x61, 0x7e, 0x41, 0x62, 0x66, 0xec, 0xe8, 0xaf, 0x21, 0x13, 0x69, 0x8e, 0xbf, 0x22, 0x1d, 0xdd,
	0x84, 0x4c, 0xa4, 0xab, 0xd0, 0xbf, 0x20, 0x27, 0xfa, 0xea, 0xa0, 0x3f, 0xea, 0xda, 0x83, 0x06,
	0x3d, 0x63, 0xc1, 0x8b, 0x38, 0xb1, 0x2a, 0x04, 0x87, 0x74, 0xdc, 0x77, 0xa8, 0x1f, 0x2b, 0x4b,
	0x26, 0x53, 0xfd, 0x43, 0xd0, 0x92, 0x7d, 0x76, 0x73, 0x89, 0xe8, 0x2d, 0x58, 0x9d, 0x51, 0x96,
	0x37, 0x18, 0xe0, 0x4b, 0x05, 0x56, 0x12, 0x0d, 0x7e, 0xb3, 0x7f, 0x87, 0x3e, 0x6d, 0x97, 0x44,
	0xfd, 0xf8, 0x8f, 0x97, 0xc9, 0x14, 0xfd, 0x13, 0x96, 0xfb, 0xd4, 0xe3, 0xa2, 0xd4, 0xc7, 0xa5,
	0xb0, 0xbe, 0xe2, 0x8b, 0xfa, 0x17, 0x0a, 0xac, 0xcf, 0xbc, 0x33, 0xde, 0xf1, 0x8c, 0x0f, 0xe1,
	0x16, 0x77, 0x38, 0xed, 0x57, 0x6c, 0xaf, 0x57, 0xa6, 0x43, 0xda, 0x16, 0x3f, 0x92, 0x52, 0xb2,
	0x2e, 0x2f, 0x6e, 0x88, 0xb3, 0x9d, 0xb8, 0x8c, 0x89, 0xb5, 0xe6, 0x90, 0xb6, 0x99, 0x3c, 0xbb,
	0x4a, 0xe2, 0x8b, 0xfa, 0x37, 0x0a, 0x14, 0xae, 0x6b, 0xea, 0x1b, 0xfc, 0x94, 0x15, 0xd8, 0xa0,
	0xe7, 0xd4, 0xee, 0xd3, 0x63, 0xbb, 0x6f, 0xf3, 0xf1, 0x85, 0x90, 0xc1, 0x07, 0xbe, 0x1a, 0xa4,
	0x23, 0xd0, 0x92, 0x37, 0xe6, 0x76, 0x15, 0x56, 0x12, 0xbf, 0x50, 0xd1, 0x0a, 0x64, 0x5e, 0x60,
	0xd2, 0xac, 0x99, 0x8d, 0x96, 0xd9, 0xc0, 0x9a, 0x12, 0x5d, 0xb0, 0x5e, 0x9a, 0x5a, 0x0a, 0xdd,
	0x82, 0xe5, 0xe9, 0xc2, 0x1e, 0xc1, 0x58, 0x53, 0xb7, 0xbf, 0x52, 0x00, 0xc2, 0xa4, 0xd0, 0x22,
	0xa8, 0xd8, 0xdc, 0xd7, 0xfe, 0x86, 0x72, 0xb0, 0x84, 0x1b, 0x66, 0xf0, 0xbc, 0xfc, 0x54, 0x45,
	0xcb, 0x90, 0xc6, 0x0d, 0x53, 0x3e, 0x31, 0xb5, 0xcf, 0x54, 0x94, 0x85, 0x45, 0x5c, 0x32, 0x2a,
	0x04, 0x3f, 0xd7, 0x3e, 0x57, 0x51, 0x1a, 0x54, 0x5c, 0x33, 0xb5, 0x1f, 0xfd, 0xd1, 0xa1, 0xa1,
	0xfd, 0xa4, 0x22, 0x0d, 0x32, 0x02, 0x11, 0xc4, 0xd3, 0x7e, 0xf6, 0x39, 0xf2, 0xd5, 0x5a, 0xd1,
	0x7e, 0x51, 0x65, 0x00, 0x82, 0x8d, 0x8a, 0xd9, 0xa8, 0x1f, 0x69, 0xbf, 0xaa, 0x68, 0x1d, 0x34,
	0x6c, 0x99, 0xe6, 0x33, 0xa3, 0x71, 0x44, 0xf0, 0xf3, 0x43, 0xdc, 0xb4, 0x9a, 0xda, 0x6f, 0xea,
	0xf6, 0xf7, 0x0a, 0x2c, 0xc7, 0x7e, 0x53, 0xa3, 0x1c, 0x80, 0xe0, 0xb5, 0xfc, 0xb3, 0x28, 0x68,
	0x19, 0x96, 0x8c, 0xca, 0x64, 0x9a, 0x42, 0x6b, 0xa0, 0x11, 0xa3, 0xb1, 0x8b, 0x5b, 0x11, 0x90,
	0x2a, 0xde, 0x3a, 0xfe, 0x6a, 0x08, 0x9d, 0x43, 0x69, 0x98, 0x33, 0x0e, 0xad, 0x3d, 0x6d, 0x5e,
	0x68, 0xbc, 0x24, 0x35, 0x0b, 0xb7, 0xea, 0x46, 0x59, 0x5b, 0x40, 0x59, 0x48, 0x4b, 0xb6, 0x98,
	0x2d, 0x0a, 0xee, 0x2e, 0xb6, 0x5a, 0x25, 0xd3, 0xdc, 0xaf, 0xe1, 0x56, 0xad, 0x51, 0x35, 0xb5,
	0xb4, 0x60, 0x34, 0x2d, 0x83, 0x58, 0x2d, 0xab, 0xde, 0xd4, 0x96, 0xe4, 0x83, 0xdc, 0x24, 0xe1,
	0x83, 0x1c, 0xd0, 0x3f, 0x60, 0x43, 0xb0, 0xea, 0xb5, 0xa6, 0xd5, 0x32, 0xab, 0x32, 0x66, 0x0d,
	0x37, 0xc5, 0x30, 0x80, 0x64, 0x4a, 0x9b, 0xf0, 0x77, 0xc7, 0xed, 0x16, 0x45, 0x05, 0x9f, 0xb2,
	0xe2, 0xf1, 0xf4, 0x5f, 0x18, 0x7e, 0xad, 0xed, 0x29, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x19, 0xde, 0xc7, 0xd7, 0x10, 0x00, 0x00,
}
